#ifndef UE4SS_SDK_ABF_Scientist_AnimBP_HPP
#define UE4SS_SDK_ABF_Scientist_AnimBP_HPP

struct FAnimBlueprintGeneratedConstantData : public FAnimBlueprintConstantData
{
    FName __NameProperty_660;                                                         // 0x0004 (size: 0x8)
    FName __NameProperty_661;                                                         // 0x000C (size: 0x8)
    TArray<float> __ArrayProperty_662;                                                // 0x0018 (size: 0x10)
    FName __NameProperty_663;                                                         // 0x0028 (size: 0x8)
    TArray<float> __ArrayProperty_664;                                                // 0x0030 (size: 0x10)
    TEnumAsByte<ESequenceEvalReinit::Type> __ByteProperty_665;                        // 0x0040 (size: 0x1)
    class UAnimSequenceBase* __AnimSequenceBase_666;                                  // 0x0048 (size: 0x8)
    TArray<float> __ArrayProperty_667;                                                // 0x0050 (size: 0x10)
    FName __NameProperty_668;                                                         // 0x0060 (size: 0x8)
    FName __NameProperty_669;                                                         // 0x0068 (size: 0x8)
    FName __NameProperty_670;                                                         // 0x0070 (size: 0x8)
    TArray<float> __ArrayProperty_671;                                                // 0x0078 (size: 0x10)
    TArray<int32> __ArrayProperty_672;                                                // 0x0088 (size: 0x10)
    TArray<float> __ArrayProperty_673;                                                // 0x0098 (size: 0x10)
    FName __NameProperty_674;                                                         // 0x00A8 (size: 0x8)
    int32 __IntProperty_675;                                                          // 0x00B0 (size: 0x4)
    FName __NameProperty_676;                                                         // 0x00B4 (size: 0x8)
    int32 __IntProperty_677;                                                          // 0x00BC (size: 0x4)
    FName __NameProperty_678;                                                         // 0x00C0 (size: 0x8)
    int32 __IntProperty_679;                                                          // 0x00C8 (size: 0x4)
    bool __BoolProperty_680;                                                          // 0x00CC (size: 0x1)
    FName __NameProperty_681;                                                         // 0x00D0 (size: 0x8)
    int32 __IntProperty_682;                                                          // 0x00D8 (size: 0x4)
    float __FloatProperty_683;                                                        // 0x00DC (size: 0x4)
    FInputScaleBiasClampConstants __StructProperty_684;                               // 0x00E0 (size: 0x2C)
    float __FloatProperty_685;                                                        // 0x010C (size: 0x4)
    EAnimSyncMethod __EnumProperty_686;                                               // 0x0110 (size: 0x1)
    TEnumAsByte<EAnimGroupRole::Type> __ByteProperty_687;                             // 0x0111 (size: 0x1)
    FName __NameProperty_688;                                                         // 0x0114 (size: 0x8)
    FName __NameProperty_689;                                                         // 0x011C (size: 0x8)
    FName __NameProperty_690;                                                         // 0x0124 (size: 0x8)
    int32 __IntProperty_691;                                                          // 0x012C (size: 0x4)
    TArray<float> __ArrayProperty_692;                                                // 0x0130 (size: 0x10)
    class UBlendProfile* __BlendProfile_693;                                          // 0x0140 (size: 0x8)
    class UCurveFloat* __CurveFloat_694;                                              // 0x0148 (size: 0x8)
    bool __BoolProperty_695;                                                          // 0x0150 (size: 0x1)
    EAlphaBlendOption __EnumProperty_696;                                             // 0x0151 (size: 0x1)
    EBlendListTransitionType __EnumProperty_697;                                      // 0x0152 (size: 0x1)
    TArray<float> __ArrayProperty_698;                                                // 0x0158 (size: 0x10)
    FAnimNodeFunctionRef __StructProperty_699;                                        // 0x0168 (size: 0x20)
    FAnimSubsystem_PropertyAccess AnimBlueprintExtension_PropertyAccess;              // 0x0188 (size: 0x80)
    FAnimSubsystem_Base AnimBlueprintExtension_Base;                                  // 0x0208 (size: 0x18)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root;                   // 0x0220 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_15;      // 0x0250 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LayeredBoneBlend_5;     // 0x0280 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Slot_8;                 // 0x02B0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LayeredBoneBlend_4;     // 0x02E0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Slot_7;                 // 0x0310 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SaveCachedPose_1;       // 0x0340 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_5;        // 0x0370 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_4;        // 0x03A0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Slot_6;                 // 0x03D0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_21;    // 0x0400 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_20;    // 0x0430 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_19;    // 0x0460 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_18;    // 0x0490 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_17;    // 0x04C0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_16;    // 0x04F0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_15;    // 0x0520 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_14;    // 0x0550 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_13;    // 0x0580 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_12;    // 0x05B0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendSpacePlayer_5;     // 0x05E0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_10;     // 0x0610 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_14;      // 0x0640 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_9;          // 0x0670 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_13;      // 0x06A0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_9;      // 0x06D0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_12;      // 0x0700 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_8;          // 0x0730 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LayeredBoneBlend_3;     // 0x0760 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendSpacePlayer_4;     // 0x0790 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequenceEvaluator_1;    // 0x07C0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_8;      // 0x07F0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendSpacePlayer_3;     // 0x0820 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_7;      // 0x0850 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_11;      // 0x0880 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LayeredBoneBlend_2;     // 0x08B0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequenceEvaluator;      // 0x08E0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_6;      // 0x0910 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendSpacePlayer_2;     // 0x0940 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_5;      // 0x0970 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendSpacePlayer_1;     // 0x09A0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_7;          // 0x09D0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendSpacePlayer;       // 0x0A00 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_6;          // 0x0A30 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_10;      // 0x0A60 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_5;          // 0x0A90 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateMachine_1;         // 0x0AC0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_4;      // 0x0AF0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_3;        // 0x0B20 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_RotationOffsetBlendSpace; // 0x0B50 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LayeredBoneBlend_1;     // 0x0B80 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_9;       // 0x0BB0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LocalToComponentSpace_1; // 0x0BE0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ComponentToLocalSpace_1; // 0x0C10 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LookAt;                 // 0x0C40 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ModifyBone_2;           // 0x0C70 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LayeredBoneBlend;       // 0x0CA0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SaveCachedPose;         // 0x0CD0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_2;        // 0x0D00 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_1;        // 0x0D30 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Slot_5;                 // 0x0D60 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByEnum;        // 0x0D90 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_8;       // 0x0DC0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_7;       // 0x0DF0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_6;       // 0x0E20 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Slot_4;                 // 0x0E50 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ModifyBone_1;           // 0x0E80 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_3;      // 0x0EB0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_5;       // 0x0EE0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_2;      // 0x0F10 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_11;    // 0x0F40 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_10;    // 0x0F70 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_9;     // 0x0FA0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_8;     // 0x0FD0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_7;     // 0x1000 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_6;     // 0x1030 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_5;     // 0x1060 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_4;     // 0x1090 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_3;     // 0x10C0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_2;     // 0x10F0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_1;     // 0x1120 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult;       // 0x1150 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_4;       // 0x1180 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_4;          // 0x11B0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_3;       // 0x11E0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_3;          // 0x1210 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Slot_3;                 // 0x1240 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_2;       // 0x1270 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_2;          // 0x12A0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Slot_2;                 // 0x12D0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_1;       // 0x1300 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_1;          // 0x1330 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer;         // 0x1360 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult;            // 0x1390 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateMachine;           // 0x13C0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_1;      // 0x13F0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose;          // 0x1420 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Slot_1;                 // 0x1450 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_PoseSnapshot;           // 0x1480 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool;        // 0x14B0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Slot;                   // 0x14E0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ModifyBone;             // 0x1510 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LocalToComponentSpace;  // 0x1540 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ComponentToLocalSpace;  // 0x1570 (size: 0x30)

}; // Size: 0x15A0

struct FAnimBlueprintGeneratedMutableData : public FAnimBlueprintMutableData
{
    float __FloatProperty;                                                            // 0x0004 (size: 0x4)
    bool __BoolProperty_0;                                                            // 0x0008 (size: 0x1)
    bool __BoolProperty_1;                                                            // 0x0009 (size: 0x1)
    bool __BoolProperty_2;                                                            // 0x000A (size: 0x1)
    float __FloatProperty_3;                                                          // 0x000C (size: 0x4)
    float __FloatProperty_4;                                                          // 0x0010 (size: 0x4)
    bool __BoolProperty_5;                                                            // 0x0014 (size: 0x1)
    float __FloatProperty_6;                                                          // 0x0018 (size: 0x4)
    bool __BoolProperty_7;                                                            // 0x001C (size: 0x1)
    float __FloatProperty_8;                                                          // 0x0020 (size: 0x4)
    bool __BoolProperty_9;                                                            // 0x0024 (size: 0x1)
    float __FloatProperty_10;                                                         // 0x0028 (size: 0x4)
    float __FloatProperty_11;                                                         // 0x002C (size: 0x4)
    float __FloatProperty_12;                                                         // 0x0030 (size: 0x4)
    bool __BoolProperty_13;                                                           // 0x0034 (size: 0x1)
    float __FloatProperty_14;                                                         // 0x0038 (size: 0x4)
    float __FloatProperty_15;                                                         // 0x003C (size: 0x4)
    uint8 __ByteProperty_16;                                                          // 0x0040 (size: 0x1)
    bool __BoolProperty_17;                                                           // 0x0041 (size: 0x1)
    bool __BoolProperty_18;                                                           // 0x0042 (size: 0x1)
    bool __BoolProperty_19;                                                           // 0x0043 (size: 0x1)
    bool __BoolProperty_20;                                                           // 0x0044 (size: 0x1)

}; // Size: 0x45

class UABF_Scientist_AnimBP_C : public UAbioticCharacterAnimInstance
{
    FPointerToUberGraphFrame UberGraphFrame;                                          // 0x0370 (size: 0x8)
    FAnimBlueprintGeneratedMutableData __AnimBlueprintMutables;                       // 0x0378 (size: 0x48)
    FAnimSubsystemInstance AnimBlueprintExtension_PropertyAccess;                     // 0x03C0 (size: 0x8)
    FAnimSubsystemInstance AnimBlueprintExtension_Base;                               // 0x03C8 (size: 0x8)
    FAnimNode_Root AnimGraphNode_Root;                                                // 0x03D0 (size: 0x20)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_15;                         // 0x03F0 (size: 0x48)
    FAnimNode_LayeredBoneBlend AnimGraphNode_LayeredBoneBlend_5;                      // 0x0438 (size: 0xF0)
    FAnimNode_Slot AnimGraphNode_Slot_8;                                              // 0x0528 (size: 0x48)
    FAnimNode_LayeredBoneBlend AnimGraphNode_LayeredBoneBlend_4;                      // 0x0570 (size: 0xF0)
    FAnimNode_Slot AnimGraphNode_Slot_7;                                              // 0x0660 (size: 0x48)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_1;                          // 0x06A8 (size: 0x80)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_5;                            // 0x0728 (size: 0x28)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_4;                            // 0x0750 (size: 0x28)
    FAnimNode_Slot AnimGraphNode_Slot_6;                                              // 0x0778 (size: 0x48)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_21;                     // 0x07C0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_20;                     // 0x07E8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_19;                     // 0x0810 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_18;                     // 0x0838 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_17;                     // 0x0860 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_16;                     // 0x0888 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_15;                     // 0x08B0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_14;                     // 0x08D8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_13;                     // 0x0900 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_12;                     // 0x0928 (size: 0x28)
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer_5;                      // 0x0950 (size: 0x70)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_10;                       // 0x09C0 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_14;                         // 0x0A08 (size: 0x48)
    FAnimNode_StateResult AnimGraphNode_StateResult_9;                                // 0x0A50 (size: 0x20)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_13;                         // 0x0A70 (size: 0x48)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_9;                        // 0x0AB8 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_12;                         // 0x0B00 (size: 0x48)
    FAnimNode_StateResult AnimGraphNode_StateResult_8;                                // 0x0B48 (size: 0x20)
    FAnimNode_LayeredBoneBlend AnimGraphNode_LayeredBoneBlend_3;                      // 0x0B68 (size: 0xF0)
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer_4;                      // 0x0C58 (size: 0x70)
    FAnimNode_SequenceEvaluator AnimGraphNode_SequenceEvaluator_1;                    // 0x0CC8 (size: 0x40)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_8;                        // 0x0D08 (size: 0x48)
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer_3;                      // 0x0D50 (size: 0x70)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_7;                        // 0x0DC0 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_11;                         // 0x0E08 (size: 0x48)
    FAnimNode_LayeredBoneBlend AnimGraphNode_LayeredBoneBlend_2;                      // 0x0E50 (size: 0xF0)
    FAnimNode_SequenceEvaluator AnimGraphNode_SequenceEvaluator;                      // 0x0F40 (size: 0x40)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_6;                        // 0x0F80 (size: 0x48)
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer_2;                      // 0x0FC8 (size: 0x70)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_5;                        // 0x1038 (size: 0x48)
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer_1;                      // 0x1080 (size: 0x70)
    FAnimNode_StateResult AnimGraphNode_StateResult_7;                                // 0x10F0 (size: 0x20)
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer;                        // 0x1110 (size: 0x70)
    FAnimNode_StateResult AnimGraphNode_StateResult_6;                                // 0x1180 (size: 0x20)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_10;                         // 0x11A0 (size: 0x48)
    FAnimNode_StateResult AnimGraphNode_StateResult_5;                                // 0x11E8 (size: 0x20)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_1;                              // 0x1208 (size: 0xC8)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_4;                        // 0x12D0 (size: 0x48)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_3;                            // 0x1318 (size: 0x28)
    FAnimNode_RotationOffsetBlendSpace AnimGraphNode_RotationOffsetBlendSpace;        // 0x1340 (size: 0x118)
    FAnimNode_LayeredBoneBlend AnimGraphNode_LayeredBoneBlend_1;                      // 0x1458 (size: 0xF0)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_9;                          // 0x1548 (size: 0x48)
    FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_1;     // 0x1590 (size: 0x20)
    FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_1;     // 0x15B0 (size: 0x20)
    FAnimNode_LookAt AnimGraphNode_LookAt;                                            // 0x15D0 (size: 0x250)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_2;                                  // 0x1820 (size: 0x128)
    FAnimNode_LayeredBoneBlend AnimGraphNode_LayeredBoneBlend;                        // 0x1948 (size: 0xF0)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose;                            // 0x1A38 (size: 0x80)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_2;                            // 0x1AB8 (size: 0x28)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_1;                            // 0x1AE0 (size: 0x28)
    FAnimNode_Slot AnimGraphNode_Slot_5;                                              // 0x1B08 (size: 0x48)
    FAnimNode_BlendListByEnum AnimGraphNode_BlendListByEnum;                          // 0x1B50 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_8;                          // 0x1B98 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_7;                          // 0x1BE0 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_6;                          // 0x1C28 (size: 0x48)
    FAnimNode_Slot AnimGraphNode_Slot_4;                                              // 0x1C70 (size: 0x48)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_1;                                  // 0x1CB8 (size: 0x128)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_3;                        // 0x1DE0 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_5;                          // 0x1E28 (size: 0x48)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_2;                        // 0x1E70 (size: 0x48)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_11;                     // 0x1EB8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_10;                     // 0x1EE0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_9;                      // 0x1F08 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_8;                      // 0x1F30 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_7;                      // 0x1F58 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_6;                      // 0x1F80 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_5;                      // 0x1FA8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_4;                      // 0x1FD0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_3;                      // 0x1FF8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_2;                      // 0x2020 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_1;                      // 0x2048 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult;                        // 0x2070 (size: 0x28)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_4;                          // 0x2098 (size: 0x48)
    FAnimNode_StateResult AnimGraphNode_StateResult_4;                                // 0x20E0 (size: 0x20)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_3;                          // 0x2100 (size: 0x48)
    FAnimNode_StateResult AnimGraphNode_StateResult_3;                                // 0x2148 (size: 0x20)
    FAnimNode_Slot AnimGraphNode_Slot_3;                                              // 0x2168 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_2;                          // 0x21B0 (size: 0x48)
    FAnimNode_StateResult AnimGraphNode_StateResult_2;                                // 0x21F8 (size: 0x20)
    FAnimNode_Slot AnimGraphNode_Slot_2;                                              // 0x2218 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_1;                          // 0x2260 (size: 0x48)
    FAnimNode_StateResult AnimGraphNode_StateResult_1;                                // 0x22A8 (size: 0x20)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer;                            // 0x22C8 (size: 0x48)
    FAnimNode_StateResult AnimGraphNode_StateResult;                                  // 0x2310 (size: 0x20)
    FAnimNode_StateMachine AnimGraphNode_StateMachine;                                // 0x2330 (size: 0xC8)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_1;                        // 0x23F8 (size: 0x48)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose;                              // 0x2440 (size: 0x28)
    FAnimNode_Slot AnimGraphNode_Slot_1;                                              // 0x2468 (size: 0x48)
    FAnimNode_PoseSnapshot AnimGraphNode_PoseSnapshot;                                // 0x24B0 (size: 0x90)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool;                          // 0x2540 (size: 0x48)
    FAnimNode_Slot AnimGraphNode_Slot;                                                // 0x2588 (size: 0x48)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone;                                    // 0x25D0 (size: 0x128)
    FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;       // 0x26F8 (size: 0x20)
    FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;       // 0x2718 (size: 0x20)
    bool K2Node_PropertyAccess_24;                                                    // 0x2738 (size: 0x1)
    bool K2Node_PropertyAccess_23;                                                    // 0x2739 (size: 0x1)
    bool K2Node_PropertyAccess_22;                                                    // 0x273A (size: 0x1)
    double K2Node_PropertyAccess_21;                                                  // 0x2740 (size: 0x8)
    double K2Node_PropertyAccess_20;                                                  // 0x2748 (size: 0x8)
    bool K2Node_PropertyAccess_19;                                                    // 0x2750 (size: 0x1)
    bool K2Node_PropertyAccess_18;                                                    // 0x2751 (size: 0x1)
    TEnumAsByte<E_AnimInteractState::Type> K2Node_PropertyAccess_17;                  // 0x2752 (size: 0x1)
    bool K2Node_PropertyAccess_16;                                                    // 0x2753 (size: 0x1)
    double K2Node_PropertyAccess_15;                                                  // 0x2758 (size: 0x8)
    bool K2Node_PropertyAccess_14;                                                    // 0x2760 (size: 0x1)
    TEnumAsByte<EMovementMode> K2Node_PropertyAccess_13;                              // 0x2761 (size: 0x1)
    bool K2Node_PropertyAccess_12;                                                    // 0x2762 (size: 0x1)
    bool K2Node_PropertyAccess_11;                                                    // 0x2763 (size: 0x1)
    bool K2Node_PropertyAccess_10;                                                    // 0x2764 (size: 0x1)
    bool K2Node_PropertyAccess_9;                                                     // 0x2765 (size: 0x1)
    bool K2Node_PropertyAccess_8;                                                     // 0x2766 (size: 0x1)
    bool K2Node_PropertyAccess_7;                                                     // 0x2767 (size: 0x1)
    FRotator K2Node_PropertyAccess_6;                                                 // 0x2768 (size: 0x18)
    FVector K2Node_PropertyAccess_5;                                                  // 0x2780 (size: 0x18)
    bool K2Node_PropertyAccess_4;                                                     // 0x2798 (size: 0x1)
    bool K2Node_PropertyAccess_3;                                                     // 0x2799 (size: 0x1)
    bool K2Node_PropertyAccess_2;                                                     // 0x279A (size: 0x1)
    double K2Node_PropertyAccess_1;                                                   // 0x27A0 (size: 0x8)
    double K2Node_PropertyAccess;                                                     // 0x27A8 (size: 0x8)
    class AAbiotic_PlayerCharacter_C* PlayerCharacter;                                // 0x27B0 (size: 0x8)
    double Time;                                                                      // 0x27B8 (size: 0x8)
    bool Is DBNO;                                                                     // 0x27C0 (size: 0x1)
    bool Is Dead;                                                                     // 0x27C1 (size: 0x1)
    double Speed;                                                                     // 0x27C8 (size: 0x8)
    bool Is Sleeping;                                                                 // 0x27D0 (size: 0x1)
    bool IsSittingInSeat;                                                             // 0x27D1 (size: 0x1)
    bool Is Viewing Wristwatch;                                                       // 0x27D2 (size: 0x1)
    bool IsCrouching;                                                                 // 0x27D3 (size: 0x1)
    bool IsUsingTerminal;                                                             // 0x27D4 (size: 0x1)
    bool Unarmed;                                                                     // 0x27D5 (size: 0x1)
    class UAimOffsetBlendSpace* AimSpace_UpperBody;                                   // 0x27D8 (size: 0x8)
    class UAnimSequence* AimSpace_BasePose;                                           // 0x27E0 (size: 0x8)
    bool RecentlyPunched;                                                             // 0x27E8 (size: 0x1)
    bool RightFootLast;                                                               // 0x27E9 (size: 0x1)
    bool IsSprinting;                                                                 // 0x27EA (size: 0x1)
    double Yaw;                                                                       // 0x27F0 (size: 0x8)
    double Pitch;                                                                     // 0x27F8 (size: 0x8)
    FVector LookAtLocation;                                                           // 0x2800 (size: 0x18)
    float SpeakingAlpha;                                                              // 0x2818 (size: 0x4)
    FRotator SpeakingJawMax;                                                          // 0x2820 (size: 0x18)
    bool Is Plug Placement Mode;                                                      // 0x2838 (size: 0x1)
    float FootfallTraceDistance;                                                      // 0x283C (size: 0x4)
    TEnumAsByte<E_AnimInteractState::Type> InteractState;                             // 0x2840 (size: 0x1)
    bool ShieldBlocking;                                                              // 0x2841 (size: 0x1)
    bool MovingCart;                                                                  // 0x2842 (size: 0x1)
    class UBlendSpace* SittingBlendspace;                                             // 0x2848 (size: 0x8)
    bool IsFalling;                                                                   // 0x2850 (size: 0x1)
    double TIPInput;                                                                  // 0x2858 (size: 0x8)
    FRotator LastRotation;                                                            // 0x2860 (size: 0x18)
    double LastTIP;                                                                   // 0x2878 (size: 0x8)
    bool TurnInPlace;                                                                 // 0x2880 (size: 0x1)
    double NormalizedTIPInput;                                                        // 0x2888 (size: 0x8)
    float DrivingAlpha;                                                               // 0x2890 (size: 0x4)
    bool Grabbed;                                                                     // 0x2894 (size: 0x1)
    bool RecentlyBlocked;                                                             // 0x2895 (size: 0x1)
    bool RecentlyUsedItem;                                                            // 0x2896 (size: 0x1)
    bool HasShield;                                                                   // 0x2897 (size: 0x1)
    class APlayerVoiceChatActor* PlayerVoiceActor;                                    // 0x2898 (size: 0x8)
    float VOIPAlpha;                                                                  // 0x28A0 (size: 0x4)
    float Direction;                                                                  // 0x28A4 (size: 0x4)
    class UAnimSequenceBase* SleepingAnim;                                            // 0x28A8 (size: 0x8)
    double GameTime;                                                                  // 0x28B0 (size: 0x8)
    FName LastTPAnimRow;                                                              // 0x28B8 (size: 0x8)
    TEnumAsByte<EPhysicalSurface> LastSurfaceType;                                    // 0x28C0 (size: 0x1)
    float IDCardAlpha;                                                                // 0x28C4 (size: 0x4)
    FVector IDLocation;                                                               // 0x28C8 (size: 0x18)
    FRotator IDRotation;                                                              // 0x28E0 (size: 0x18)
    FVector IDScale;                                                                  // 0x28F8 (size: 0x18)

    void AnimGraph(FPoseLink& AnimGraph);
    void ThreadSafe_CachePlayerCharacterData();
    void BlueprintThreadSafeUpdateAnimation(float DeltaTime);
    void UpdateTIP();
    void OnLoaded_9B2BEA70432984D9E96AE1A8569C0261(class UObject* Loaded);
    void OnLoaded_9564D4314E710F8FAD70A29E16A3DA61(class UObject* Loaded);
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABF_Scientist_AnimBP_AnimGraphNode_LayeredBoneBlend_CD7F6F5D48A6532ADF973F8CBDC3697C();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABF_Scientist_AnimBP_AnimGraphNode_LookAt_F7F3FC8840B461A35831A18D58E2722F();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABF_Scientist_AnimBP_AnimGraphNode_LayeredBoneBlend_127BA6104074CC756FCA94A8DE04156A();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABF_Scientist_AnimBP_AnimGraphNode_BlendListByBool_38D8FDD3428D3E98E6F1528602357D2E();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABF_Scientist_AnimBP_AnimGraphNode_LayeredBoneBlend_5057A7A24D5C2C58E95D5B9EE70E7647();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABF_Scientist_AnimBP_AnimGraphNode_TransitionResult_84574A0A4A9C5ADAF1CE668613CA0F95();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABF_Scientist_AnimBP_AnimGraphNode_TransitionResult_657278AF42835B83AB3362817B6E8FF9();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABF_Scientist_AnimBP_AnimGraphNode_TransitionResult_605D69804F182EF932FBB8937E0E3632();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABF_Scientist_AnimBP_AnimGraphNode_TransitionResult_E13EE19D4031FB9C5D4D4F853E7D8150();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABF_Scientist_AnimBP_AnimGraphNode_TransitionResult_28845A294A1F2023E79C96ACDC2F07B1();
    void BlueprintUpdateAnimation(float DeltaTimeX);
    void Set_RecentlyPunched();
    void AnimNotify_Footfall_Left();
    void AnimNotify_Footfall_Right();
    void BlueprintBeginPlay();
    void OnBlockReaction_Event();
    void OnMicrophoneVolumeReceived(float Volume);
    void AnimNotify_SitValidate();
    void ExecuteUbergraph_ABF_Scientist_AnimBP(int32 EntryPoint);
}; // Size: 0x2910

#endif
