#ifndef UE4SS_SDK_ABF_Scientist_AnimBP_HPP
#define UE4SS_SDK_ABF_Scientist_AnimBP_HPP

struct FAnimBlueprintGeneratedConstantData : public FAnimBlueprintConstantData
{
    FName __NameProperty_605;                                                         // 0x0004 (size: 0x8)
    FName __NameProperty_606;                                                         // 0x000C (size: 0x8)
    TArray<float> __ArrayProperty_607;                                                // 0x0018 (size: 0x10)
    FName __NameProperty_608;                                                         // 0x0028 (size: 0x8)
    TArray<float> __ArrayProperty_609;                                                // 0x0030 (size: 0x10)
    TEnumAsByte<ESequenceEvalReinit::Type> __ByteProperty_610;                        // 0x0040 (size: 0x1)
    class UAnimSequenceBase* __AnimSequenceBase_611;                                  // 0x0048 (size: 0x8)
    TArray<float> __ArrayProperty_612;                                                // 0x0050 (size: 0x10)
    FName __NameProperty_613;                                                         // 0x0060 (size: 0x8)
    FName __NameProperty_614;                                                         // 0x0068 (size: 0x8)
    FName __NameProperty_615;                                                         // 0x0070 (size: 0x8)
    TArray<float> __ArrayProperty_616;                                                // 0x0078 (size: 0x10)
    TArray<float> __ArrayProperty_617;                                                // 0x0088 (size: 0x10)
    TArray<int32> __ArrayProperty_618;                                                // 0x0098 (size: 0x10)
    TArray<float> __ArrayProperty_619;                                                // 0x00A8 (size: 0x10)
    FName __NameProperty_620;                                                         // 0x00B8 (size: 0x8)
    int32 __IntProperty_621;                                                          // 0x00C0 (size: 0x4)
    FName __NameProperty_622;                                                         // 0x00C4 (size: 0x8)
    int32 __IntProperty_623;                                                          // 0x00CC (size: 0x4)
    FName __NameProperty_624;                                                         // 0x00D0 (size: 0x8)
    int32 __IntProperty_625;                                                          // 0x00D8 (size: 0x4)
    bool __BoolProperty_626;                                                          // 0x00DC (size: 0x1)
    FName __NameProperty_627;                                                         // 0x00E0 (size: 0x8)
    int32 __IntProperty_628;                                                          // 0x00E8 (size: 0x4)
    float __FloatProperty_629;                                                        // 0x00EC (size: 0x4)
    FInputScaleBiasClampConstants __StructProperty_630;                               // 0x00F0 (size: 0x2C)
    float __FloatProperty_631;                                                        // 0x011C (size: 0x4)
    EAnimSyncMethod __EnumProperty_632;                                               // 0x0120 (size: 0x1)
    TEnumAsByte<EAnimGroupRole::Type> __ByteProperty_633;                             // 0x0121 (size: 0x1)
    FName __NameProperty_634;                                                         // 0x0124 (size: 0x8)
    FName __NameProperty_635;                                                         // 0x012C (size: 0x8)
    FName __NameProperty_636;                                                         // 0x0134 (size: 0x8)
    int32 __IntProperty_637;                                                          // 0x013C (size: 0x4)
    class UBlendProfile* __BlendProfile_638;                                          // 0x0140 (size: 0x8)
    class UCurveFloat* __CurveFloat_639;                                              // 0x0148 (size: 0x8)
    bool __BoolProperty_640;                                                          // 0x0150 (size: 0x1)
    EAlphaBlendOption __EnumProperty_641;                                             // 0x0151 (size: 0x1)
    EBlendListTransitionType __EnumProperty_642;                                      // 0x0152 (size: 0x1)
    TArray<float> __ArrayProperty_643;                                                // 0x0158 (size: 0x10)
    FAnimNodeFunctionRef __StructProperty_644;                                        // 0x0168 (size: 0x20)
    FAnimSubsystem_PropertyAccess AnimBlueprintExtension_PropertyAccess;              // 0x0188 (size: 0x80)
    FAnimSubsystem_Base AnimBlueprintExtension_Base;                                  // 0x0208 (size: 0x18)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root;                   // 0x0220 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_15;      // 0x0250 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LayeredBoneBlend_4;     // 0x0280 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Slot_6;                 // 0x02B0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LayeredBoneBlend_3;     // 0x02E0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Slot_5;                 // 0x0310 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SaveCachedPose_1;       // 0x0340 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_5;        // 0x0370 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_4;        // 0x03A0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_21;    // 0x03D0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_20;    // 0x0400 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_19;    // 0x0430 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_18;    // 0x0460 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_17;    // 0x0490 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_16;    // 0x04C0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_15;    // 0x04F0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_14;    // 0x0520 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_13;    // 0x0550 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_12;    // 0x0580 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendSpacePlayer_4;     // 0x05B0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_9;      // 0x05E0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_14;      // 0x0610 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_9;          // 0x0640 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_13;      // 0x0670 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_8;      // 0x06A0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_12;      // 0x06D0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_8;          // 0x0700 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendSpacePlayer_3;     // 0x0730 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_7;      // 0x0760 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_11;      // 0x0790 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LayeredBoneBlend_2;     // 0x07C0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequenceEvaluator;      // 0x07F0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_6;      // 0x0820 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendSpacePlayer_2;     // 0x0850 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_5;      // 0x0880 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendSpacePlayer_1;     // 0x08B0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_7;          // 0x08E0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendSpacePlayer;       // 0x0910 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_6;          // 0x0940 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_10;      // 0x0970 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_5;          // 0x09A0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateMachine_1;         // 0x09D0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_4;      // 0x0A00 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_3;        // 0x0A30 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_RotationOffsetBlendSpace; // 0x0A60 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LayeredBoneBlend_1;     // 0x0A90 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_9;       // 0x0AC0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LocalToComponentSpace;  // 0x0AF0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ComponentToLocalSpace;  // 0x0B20 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LookAt;                 // 0x0B50 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ModifyBone_1;           // 0x0B80 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LayeredBoneBlend;       // 0x0BB0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SaveCachedPose;         // 0x0BE0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_2;        // 0x0C10 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_1;        // 0x0C40 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_3;      // 0x0C70 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Slot_4;                 // 0x0CA0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByEnum;        // 0x0CD0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_8;       // 0x0D00 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_7;       // 0x0D30 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_6;       // 0x0D60 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Slot_3;                 // 0x0D90 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ModifyBone;             // 0x0DC0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_2;      // 0x0DF0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_5;       // 0x0E20 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_1;      // 0x0E50 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_11;    // 0x0E80 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_10;    // 0x0EB0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_9;     // 0x0EE0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_8;     // 0x0F10 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_7;     // 0x0F40 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_6;     // 0x0F70 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_5;     // 0x0FA0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_4;     // 0x0FD0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_3;     // 0x1000 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_2;     // 0x1030 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_1;     // 0x1060 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult;       // 0x1090 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_4;       // 0x10C0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_4;          // 0x10F0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_3;       // 0x1120 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_3;          // 0x1150 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Slot_2;                 // 0x1180 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_2;       // 0x11B0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_2;          // 0x11E0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Slot_1;                 // 0x1210 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_1;       // 0x1240 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_1;          // 0x1270 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer;         // 0x12A0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult;            // 0x12D0 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateMachine;           // 0x1300 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool;        // 0x1330 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose;          // 0x1360 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Slot;                   // 0x1390 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_PoseSnapshot;           // 0x13C0 (size: 0x30)

}; // Size: 0x13F0

struct FAnimBlueprintGeneratedMutableData : public FAnimBlueprintMutableData
{
    float __FloatProperty;                                                            // 0x0004 (size: 0x4)
    bool __BoolProperty_0;                                                            // 0x0008 (size: 0x1)
    bool __BoolProperty_1;                                                            // 0x0009 (size: 0x1)
    float __FloatProperty_2;                                                          // 0x000C (size: 0x4)
    float __FloatProperty_3;                                                          // 0x0010 (size: 0x4)
    bool __BoolProperty_4;                                                            // 0x0014 (size: 0x1)
    float __FloatProperty_5;                                                          // 0x0018 (size: 0x4)
    bool __BoolProperty_6;                                                            // 0x001C (size: 0x1)
    float __FloatProperty_7;                                                          // 0x0020 (size: 0x4)
    bool __BoolProperty_8;                                                            // 0x0024 (size: 0x1)
    float __FloatProperty_9;                                                          // 0x0028 (size: 0x4)
    float __FloatProperty_10;                                                         // 0x002C (size: 0x4)
    float __FloatProperty_11;                                                         // 0x0030 (size: 0x4)
    bool __BoolProperty_12;                                                           // 0x0034 (size: 0x1)
    float __FloatProperty_13;                                                         // 0x0038 (size: 0x4)
    float __FloatProperty_14;                                                         // 0x003C (size: 0x4)
    bool __BoolProperty_15;                                                           // 0x0040 (size: 0x1)
    uint8 __ByteProperty_16;                                                          // 0x0041 (size: 0x1)
    bool __BoolProperty_17;                                                           // 0x0042 (size: 0x1)
    bool __BoolProperty_18;                                                           // 0x0043 (size: 0x1)
    bool __BoolProperty_19;                                                           // 0x0044 (size: 0x1)

}; // Size: 0x45

class UABF_Scientist_AnimBP_C : public UAbioticCharacterAnimInstance
{
    FPointerToUberGraphFrame UberGraphFrame;                                          // 0x0370 (size: 0x8)
    FAnimBlueprintGeneratedMutableData __AnimBlueprintMutables;                       // 0x0378 (size: 0x48)
    FAnimSubsystemInstance AnimBlueprintExtension_PropertyAccess;                     // 0x03C0 (size: 0x8)
    FAnimSubsystemInstance AnimBlueprintExtension_Base;                               // 0x03C8 (size: 0x8)
    FAnimNode_Root AnimGraphNode_Root;                                                // 0x03D0 (size: 0x20)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_15;                         // 0x03F0 (size: 0x48)
    FAnimNode_LayeredBoneBlend AnimGraphNode_LayeredBoneBlend_4;                      // 0x0438 (size: 0xF0)
    FAnimNode_Slot AnimGraphNode_Slot_6;                                              // 0x0528 (size: 0x48)
    FAnimNode_LayeredBoneBlend AnimGraphNode_LayeredBoneBlend_3;                      // 0x0570 (size: 0xF0)
    FAnimNode_Slot AnimGraphNode_Slot_5;                                              // 0x0660 (size: 0x48)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_1;                          // 0x06A8 (size: 0x80)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_5;                            // 0x0728 (size: 0x28)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_4;                            // 0x0750 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_21;                     // 0x0778 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_20;                     // 0x07A0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_19;                     // 0x07C8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_18;                     // 0x07F0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_17;                     // 0x0818 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_16;                     // 0x0840 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_15;                     // 0x0868 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_14;                     // 0x0890 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_13;                     // 0x08B8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_12;                     // 0x08E0 (size: 0x28)
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer_4;                      // 0x0908 (size: 0x70)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_9;                        // 0x0978 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_14;                         // 0x09C0 (size: 0x48)
    FAnimNode_StateResult AnimGraphNode_StateResult_9;                                // 0x0A08 (size: 0x20)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_13;                         // 0x0A28 (size: 0x48)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_8;                        // 0x0A70 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_12;                         // 0x0AB8 (size: 0x48)
    FAnimNode_StateResult AnimGraphNode_StateResult_8;                                // 0x0B00 (size: 0x20)
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer_3;                      // 0x0B20 (size: 0x70)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_7;                        // 0x0B90 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_11;                         // 0x0BD8 (size: 0x48)
    FAnimNode_LayeredBoneBlend AnimGraphNode_LayeredBoneBlend_2;                      // 0x0C20 (size: 0xF0)
    FAnimNode_SequenceEvaluator AnimGraphNode_SequenceEvaluator;                      // 0x0D10 (size: 0x40)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_6;                        // 0x0D50 (size: 0x48)
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer_2;                      // 0x0D98 (size: 0x70)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_5;                        // 0x0E08 (size: 0x48)
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer_1;                      // 0x0E50 (size: 0x70)
    FAnimNode_StateResult AnimGraphNode_StateResult_7;                                // 0x0EC0 (size: 0x20)
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer;                        // 0x0EE0 (size: 0x70)
    FAnimNode_StateResult AnimGraphNode_StateResult_6;                                // 0x0F50 (size: 0x20)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_10;                         // 0x0F70 (size: 0x48)
    FAnimNode_StateResult AnimGraphNode_StateResult_5;                                // 0x0FB8 (size: 0x20)
    FAnimNode_StateMachine AnimGraphNode_StateMachine_1;                              // 0x0FD8 (size: 0xC8)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_4;                        // 0x10A0 (size: 0x48)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_3;                            // 0x10E8 (size: 0x28)
    FAnimNode_RotationOffsetBlendSpace AnimGraphNode_RotationOffsetBlendSpace;        // 0x1110 (size: 0x118)
    FAnimNode_LayeredBoneBlend AnimGraphNode_LayeredBoneBlend_1;                      // 0x1228 (size: 0xF0)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_9;                          // 0x1318 (size: 0x48)
    FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;       // 0x1360 (size: 0x20)
    FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;       // 0x1380 (size: 0x20)
    FAnimNode_LookAt AnimGraphNode_LookAt;                                            // 0x13A0 (size: 0x250)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_1;                                  // 0x15F0 (size: 0x128)
    FAnimNode_LayeredBoneBlend AnimGraphNode_LayeredBoneBlend;                        // 0x1718 (size: 0xF0)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose;                            // 0x1808 (size: 0x80)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_2;                            // 0x1888 (size: 0x28)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_1;                            // 0x18B0 (size: 0x28)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_3;                        // 0x18D8 (size: 0x48)
    FAnimNode_Slot AnimGraphNode_Slot_4;                                              // 0x1920 (size: 0x48)
    FAnimNode_BlendListByEnum AnimGraphNode_BlendListByEnum;                          // 0x1968 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_8;                          // 0x19B0 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_7;                          // 0x19F8 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_6;                          // 0x1A40 (size: 0x48)
    FAnimNode_Slot AnimGraphNode_Slot_3;                                              // 0x1A88 (size: 0x48)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone;                                    // 0x1AD0 (size: 0x128)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_2;                        // 0x1BF8 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_5;                          // 0x1C40 (size: 0x48)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_1;                        // 0x1C88 (size: 0x48)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_11;                     // 0x1CD0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_10;                     // 0x1CF8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_9;                      // 0x1D20 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_8;                      // 0x1D48 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_7;                      // 0x1D70 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_6;                      // 0x1D98 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_5;                      // 0x1DC0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_4;                      // 0x1DE8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_3;                      // 0x1E10 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_2;                      // 0x1E38 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_1;                      // 0x1E60 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult;                        // 0x1E88 (size: 0x28)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_4;                          // 0x1EB0 (size: 0x48)
    FAnimNode_StateResult AnimGraphNode_StateResult_4;                                // 0x1EF8 (size: 0x20)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_3;                          // 0x1F18 (size: 0x48)
    FAnimNode_StateResult AnimGraphNode_StateResult_3;                                // 0x1F60 (size: 0x20)
    FAnimNode_Slot AnimGraphNode_Slot_2;                                              // 0x1F80 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_2;                          // 0x1FC8 (size: 0x48)
    FAnimNode_StateResult AnimGraphNode_StateResult_2;                                // 0x2010 (size: 0x20)
    FAnimNode_Slot AnimGraphNode_Slot_1;                                              // 0x2030 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_1;                          // 0x2078 (size: 0x48)
    FAnimNode_StateResult AnimGraphNode_StateResult_1;                                // 0x20C0 (size: 0x20)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer;                            // 0x20E0 (size: 0x48)
    FAnimNode_StateResult AnimGraphNode_StateResult;                                  // 0x2128 (size: 0x20)
    FAnimNode_StateMachine AnimGraphNode_StateMachine;                                // 0x2148 (size: 0xC8)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool;                          // 0x2210 (size: 0x48)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose;                              // 0x2258 (size: 0x28)
    FAnimNode_Slot AnimGraphNode_Slot;                                                // 0x2280 (size: 0x48)
    FAnimNode_PoseSnapshot AnimGraphNode_PoseSnapshot;                                // 0x22C8 (size: 0x90)
    class AAbiotic_PlayerCharacter_C* PlayerCharacter;                                // 0x2358 (size: 0x8)
    double Time;                                                                      // 0x2360 (size: 0x8)
    bool Is DBNO;                                                                     // 0x2368 (size: 0x1)
    bool Is Dead;                                                                     // 0x2369 (size: 0x1)
    double Speed;                                                                     // 0x2370 (size: 0x8)
    bool Is Sleeping;                                                                 // 0x2378 (size: 0x1)
    bool IsSittingInSeat;                                                             // 0x2379 (size: 0x1)
    bool Is Viewing Wristwatch;                                                       // 0x237A (size: 0x1)
    bool IsCrouching;                                                                 // 0x237B (size: 0x1)
    bool IsUsingTerminal;                                                             // 0x237C (size: 0x1)
    bool Unarmed;                                                                     // 0x237D (size: 0x1)
    class UAimOffsetBlendSpace* AimSpace_UpperBody;                                   // 0x2380 (size: 0x8)
    class UAnimSequence* AimSpace_BasePose;                                           // 0x2388 (size: 0x8)
    bool RecentlyPunched;                                                             // 0x2390 (size: 0x1)
    bool RightFootLast;                                                               // 0x2391 (size: 0x1)
    bool IsSprinting;                                                                 // 0x2392 (size: 0x1)
    double Yaw;                                                                       // 0x2398 (size: 0x8)
    double Pitch;                                                                     // 0x23A0 (size: 0x8)
    FVector LookAtLocation;                                                           // 0x23A8 (size: 0x18)
    float SpeakingAlpha;                                                              // 0x23C0 (size: 0x4)
    FRotator SpeakingJawMax;                                                          // 0x23C8 (size: 0x18)
    bool Is Plug Placement Mode;                                                      // 0x23E0 (size: 0x1)
    float FootfallTraceDistance;                                                      // 0x23E4 (size: 0x4)
    TEnumAsByte<E_AnimInteractState::Type> InteractState;                             // 0x23E8 (size: 0x1)
    bool ShieldBlocking;                                                              // 0x23E9 (size: 0x1)
    bool MovingCart;                                                                  // 0x23EA (size: 0x1)
    class UBlendSpace* SittingBlendspace;                                             // 0x23F0 (size: 0x8)
    bool IsFalling;                                                                   // 0x23F8 (size: 0x1)
    double TIPInput;                                                                  // 0x2400 (size: 0x8)
    FRotator LastRotation;                                                            // 0x2408 (size: 0x18)
    double LastTIP;                                                                   // 0x2420 (size: 0x8)
    bool TurnInPlace;                                                                 // 0x2428 (size: 0x1)
    double NormalizedTIPInput;                                                        // 0x2430 (size: 0x8)
    float DrivingAlpha;                                                               // 0x2438 (size: 0x4)
    bool Grabbed;                                                                     // 0x243C (size: 0x1)
    bool RecentlyBlocked;                                                             // 0x243D (size: 0x1)
    bool RecentlyUsedItem;                                                            // 0x243E (size: 0x1)
    bool HasShield;                                                                   // 0x243F (size: 0x1)
    class APlayerVoiceChatActor* PlayerVoiceActor;                                    // 0x2440 (size: 0x8)
    float VOIPAlpha;                                                                  // 0x2448 (size: 0x4)
    float Direction;                                                                  // 0x244C (size: 0x4)
    class UAnimSequenceBase* SleepingAnim;                                            // 0x2450 (size: 0x8)

    void AnimGraph(FPoseLink& AnimGraph);
    void UpdateTIP();
    void OnLoaded_9B2BEA70432984D9E96AE1A8569C0261(class UObject* Loaded);
    void OnLoaded_9564D4314E710F8FAD70A29E16A3DA61(class UObject* Loaded);
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABF_Scientist_AnimBP_AnimGraphNode_LayeredBoneBlend_CD7F6F5D48A6532ADF973F8CBDC3697C();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABF_Scientist_AnimBP_AnimGraphNode_LookAt_F7F3FC8840B461A35831A18D58E2722F();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABF_Scientist_AnimBP_AnimGraphNode_LayeredBoneBlend_127BA6104074CC756FCA94A8DE04156A();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABF_Scientist_AnimBP_AnimGraphNode_BlendListByBool_38D8FDD3428D3E98E6F1528602357D2E();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABF_Scientist_AnimBP_AnimGraphNode_LayeredBoneBlend_5057A7A24D5C2C58E95D5B9EE70E7647();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABF_Scientist_AnimBP_AnimGraphNode_TransitionResult_84574A0A4A9C5ADAF1CE668613CA0F95();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABF_Scientist_AnimBP_AnimGraphNode_TransitionResult_657278AF42835B83AB3362817B6E8FF9();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABF_Scientist_AnimBP_AnimGraphNode_TransitionResult_605D69804F182EF932FBB8937E0E3632();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABF_Scientist_AnimBP_AnimGraphNode_TransitionResult_E13EE19D4031FB9C5D4D4F853E7D8150();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABF_Scientist_AnimBP_AnimGraphNode_TransitionResult_28845A294A1F2023E79C96ACDC2F07B1();
    void BlueprintUpdateAnimation(float DeltaTimeX);
    void Set_RecentlyPunched();
    void AnimNotify_Footfall_Left();
    void AnimNotify_Footfall_Right();
    void BlueprintBeginPlay();
    void OnBlockReaction_Event();
    void OnMicrophoneVolumeReceived(float Volume);
    void ExecuteUbergraph_ABF_Scientist_AnimBP(int32 EntryPoint);
}; // Size: 0x2458

#endif
