#ifndef UE4SS_SDK_Deployed_Furniture_Chair_Executive_01_Relevant_HPP
#define UE4SS_SDK_Deployed_Furniture_Chair_Executive_01_Relevant_HPP

class ADeployed_Furniture_Chair_Executive_01_Relevant_C : public ADeployed_Furniture_Chair_Executive_01_C
{
}; // Size: 0x958

#endif
