#ifndef UE4SS_SDK_FPArms_AnimBP_HPP
#define UE4SS_SDK_FPArms_AnimBP_HPP

struct FAnimBlueprintGeneratedConstantData : public FAnimBlueprintConstantData
{
    FName __NameProperty_521;                                                         // 0x0004 (size: 0x8)
    FName __NameProperty_522;                                                         // 0x000C (size: 0x8)
    int32 __IntProperty_523;                                                          // 0x0014 (size: 0x4)
    FName __NameProperty_524;                                                         // 0x0018 (size: 0x8)
    int32 __IntProperty_525;                                                          // 0x0020 (size: 0x4)
    FName __NameProperty_526;                                                         // 0x0024 (size: 0x8)
    int32 __IntProperty_527;                                                          // 0x002C (size: 0x4)
    TArray<float> __ArrayProperty_528;                                                // 0x0030 (size: 0x10)
    TEnumAsByte<EAnimGroupRole::Type> __ByteProperty_529;                             // 0x0040 (size: 0x1)
    FName __NameProperty_530;                                                         // 0x0044 (size: 0x8)
    int32 __IntProperty_531;                                                          // 0x004C (size: 0x4)
    FName __NameProperty_532;                                                         // 0x0050 (size: 0x8)
    FName __NameProperty_533;                                                         // 0x0058 (size: 0x8)
    EAlphaBlendOption __EnumProperty_534;                                             // 0x0060 (size: 0x1)
    TArray<float> __ArrayProperty_535;                                                // 0x0068 (size: 0x10)
    TArray<float> __ArrayProperty_536;                                                // 0x0078 (size: 0x10)
    TArray<float> __ArrayProperty_537;                                                // 0x0088 (size: 0x10)
    EAlphaBlendOption __EnumProperty_538;                                             // 0x0098 (size: 0x1)
    TArray<float> __ArrayProperty_539;                                                // 0x00A0 (size: 0x10)
    int32 __IntProperty_540;                                                          // 0x00B0 (size: 0x4)
    class UAnimSequenceBase* __AnimSequenceBase_541;                                  // 0x00B8 (size: 0x8)
    TArray<float> __ArrayProperty_542;                                                // 0x00C0 (size: 0x10)
    TArray<int32> __ArrayProperty_543;                                                // 0x00D0 (size: 0x10)
    class UBlendProfile* __BlendProfile_544;                                          // 0x00E0 (size: 0x8)
    class UCurveFloat* __CurveFloat_545;                                              // 0x00E8 (size: 0x8)
    EAlphaBlendOption __EnumProperty_546;                                             // 0x00F0 (size: 0x1)
    EBlendListTransitionType __EnumProperty_547;                                      // 0x00F1 (size: 0x1)
    TArray<float> __ArrayProperty_548;                                                // 0x00F8 (size: 0x10)
    EAnimSyncMethod __EnumProperty_549;                                               // 0x0108 (size: 0x1)
    TEnumAsByte<EAnimGroupRole::Type> __ByteProperty_550;                             // 0x0109 (size: 0x1)
    FName __NameProperty_551;                                                         // 0x010C (size: 0x8)
    FAnimNodeFunctionRef __StructProperty_552;                                        // 0x0118 (size: 0x20)
    bool __BoolProperty_553;                                                          // 0x0138 (size: 0x1)
    float __FloatProperty_554;                                                        // 0x013C (size: 0x4)
    FInputScaleBiasClampConstants __StructProperty_555;                               // 0x0140 (size: 0x2C)
    float __FloatProperty_556;                                                        // 0x016C (size: 0x4)
    bool __BoolProperty_557;                                                          // 0x0170 (size: 0x1)
    EAnimSyncMethod __EnumProperty_558;                                               // 0x0171 (size: 0x1)
    TEnumAsByte<EAnimGroupRole::Type> __ByteProperty_559;                             // 0x0172 (size: 0x1)
    FName __NameProperty_560;                                                         // 0x0174 (size: 0x8)
    FAnimSubsystem_PropertyAccess AnimBlueprintExtension_PropertyAccess;              // 0x0180 (size: 0x80)
    FAnimSubsystem_Base AnimBlueprintExtension_Base;                                  // 0x0200 (size: 0x18)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_18;      // 0x0218 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_17;      // 0x0248 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_16;      // 0x0278 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByEnum_1;      // 0x02A8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_4;        // 0x02D8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_15;      // 0x0308 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_3;        // 0x0338 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_14;      // 0x0368 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_13;      // 0x0398 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_12;      // 0x03C8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SaveCachedPose_1;       // 0x03F8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_8;      // 0x0428 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LayeredBoneBlend_1;     // 0x0458 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root;                   // 0x0488 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_7;      // 0x04B8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_11;      // 0x04E8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_6;      // 0x0518 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Slot_5;                 // 0x0548 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_11;    // 0x0578 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_10;    // 0x05A8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_9;     // 0x05D8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_8;     // 0x0608 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_7;     // 0x0638 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_6;     // 0x0668 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_5;     // 0x0698 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_4;     // 0x06C8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_3;     // 0x06F8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_2;     // 0x0728 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_1;     // 0x0758 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult;       // 0x0788 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ComponentToLocalSpace_5; // 0x07B8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LocalToComponentSpace_5; // 0x07E8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ModifyBone_5;           // 0x0818 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_10;      // 0x0848 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_4;          // 0x0878 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ComponentToLocalSpace_4; // 0x08A8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LocalToComponentSpace_4; // 0x08D8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ModifyBone_4;           // 0x0908 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Slot_4;                 // 0x0938 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_9;       // 0x0968 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_3;          // 0x0998 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ComponentToLocalSpace_3; // 0x09C8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LocalToComponentSpace_3; // 0x09F8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ModifyBone_3;           // 0x0A28 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Slot_3;                 // 0x0A58 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_8;       // 0x0A88 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_2;          // 0x0AB8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ComponentToLocalSpace_2; // 0x0AE8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LocalToComponentSpace_2; // 0x0B18 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ModifyBone_2;           // 0x0B48 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Slot_2;                 // 0x0B78 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_5;      // 0x0BA8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_7;       // 0x0BD8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_6;       // 0x0C08 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_1;          // 0x0C38 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ComponentToLocalSpace_1; // 0x0C68 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LocalToComponentSpace_1; // 0x0C98 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ModifyBone_1;           // 0x0CC8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_5;       // 0x0CF8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult;            // 0x0D28 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateMachine;           // 0x0D58 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Slot_1;                 // 0x0D88 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_2;        // 0x0DB8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_4;      // 0x0DE8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ModifyBone;             // 0x0E18 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ComponentToLocalSpace;  // 0x0E48 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LocalToComponentSpace;  // 0x0E78 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_4;       // 0x0EA8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_3;      // 0x0ED8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_2;      // 0x0F08 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Slot;                   // 0x0F38 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendSpacePlayer;       // 0x0F68 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_1;      // 0x0F98 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequenceEvaluator;      // 0x0FC8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByEnum;        // 0x0FF8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LayeredBoneBlend;       // 0x1028 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool;        // 0x1058 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_3;       // 0x1088 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SaveCachedPose;         // 0x10B8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_1;        // 0x10E8 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose;          // 0x1118 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_2;       // 0x1148 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_1;       // 0x1178 (size: 0x30)
    FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer;         // 0x11A8 (size: 0x30)

}; // Size: 0x11D8

struct FAnimBlueprintGeneratedMutableData : public FAnimBlueprintMutableData
{
    uint8 __ByteProperty;                                                             // 0x0001 (size: 0x1)
    float __FloatProperty_0;                                                          // 0x0004 (size: 0x4)
    float __FloatProperty_1;                                                          // 0x0008 (size: 0x4)
    bool __BoolProperty_2;                                                            // 0x000C (size: 0x1)
    bool __BoolProperty_3;                                                            // 0x000D (size: 0x1)
    bool __BoolProperty_4;                                                            // 0x000E (size: 0x1)
    bool __BoolProperty_5;                                                            // 0x000F (size: 0x1)
    bool __BoolProperty_6;                                                            // 0x0010 (size: 0x1)
    bool __BoolProperty_7;                                                            // 0x0011 (size: 0x1)
    bool __BoolProperty_8;                                                            // 0x0012 (size: 0x1)
    float __FloatProperty_9;                                                          // 0x0014 (size: 0x4)
    float __FloatProperty_10;                                                         // 0x0018 (size: 0x4)
    bool __BoolProperty_11;                                                           // 0x001C (size: 0x1)
    float __FloatProperty_12;                                                         // 0x0020 (size: 0x4)
    uint8 __ByteProperty_13;                                                          // 0x0024 (size: 0x1)
    bool __BoolProperty_14;                                                           // 0x0025 (size: 0x1)
    float __FloatProperty_15;                                                         // 0x0028 (size: 0x4)
    float __FloatProperty_16;                                                         // 0x002C (size: 0x4)

}; // Size: 0x30

class UFPArms_AnimBP_C : public UFPArmsAnimInstance
{
    FPointerToUberGraphFrame UberGraphFrame;                                          // 0x0370 (size: 0x8)
    FAnimBlueprintGeneratedMutableData __AnimBlueprintMutables;                       // 0x0378 (size: 0x30)
    FAnimSubsystemInstance AnimBlueprintExtension_PropertyAccess;                     // 0x03A8 (size: 0x8)
    FAnimSubsystemInstance AnimBlueprintExtension_Base;                               // 0x03B0 (size: 0x8)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_18;                         // 0x03B8 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_17;                         // 0x0400 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_16;                         // 0x0448 (size: 0x48)
    FAnimNode_BlendListByEnum AnimGraphNode_BlendListByEnum_1;                        // 0x0490 (size: 0x48)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_4;                            // 0x04D8 (size: 0x28)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_15;                         // 0x0500 (size: 0x48)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_3;                            // 0x0548 (size: 0x28)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_14;                         // 0x0570 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_13;                         // 0x05B8 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_12;                         // 0x0600 (size: 0x48)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose_1;                          // 0x0648 (size: 0x80)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_8;                        // 0x06C8 (size: 0x48)
    FAnimNode_LayeredBoneBlend AnimGraphNode_LayeredBoneBlend_1;                      // 0x0710 (size: 0xF0)
    FAnimNode_Root AnimGraphNode_Root;                                                // 0x0800 (size: 0x20)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_7;                        // 0x0820 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_11;                         // 0x0868 (size: 0x48)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_6;                        // 0x08B0 (size: 0x48)
    FAnimNode_Slot AnimGraphNode_Slot_5;                                              // 0x08F8 (size: 0x48)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_11;                     // 0x0940 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_10;                     // 0x0968 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_9;                      // 0x0990 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_8;                      // 0x09B8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_7;                      // 0x09E0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_6;                      // 0x0A08 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_5;                      // 0x0A30 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_4;                      // 0x0A58 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_3;                      // 0x0A80 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_2;                      // 0x0AA8 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_1;                      // 0x0AD0 (size: 0x28)
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult;                        // 0x0AF8 (size: 0x28)
    FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_5;     // 0x0B20 (size: 0x20)
    FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_5;     // 0x0B40 (size: 0x20)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_5;                                  // 0x0B60 (size: 0x128)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_10;                         // 0x0C88 (size: 0x48)
    FAnimNode_StateResult AnimGraphNode_StateResult_4;                                // 0x0CD0 (size: 0x20)
    FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_4;     // 0x0CF0 (size: 0x20)
    FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_4;     // 0x0D10 (size: 0x20)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_4;                                  // 0x0D30 (size: 0x128)
    FAnimNode_Slot AnimGraphNode_Slot_4;                                              // 0x0E58 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_9;                          // 0x0EA0 (size: 0x48)
    FAnimNode_StateResult AnimGraphNode_StateResult_3;                                // 0x0EE8 (size: 0x20)
    FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_3;     // 0x0F08 (size: 0x20)
    FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_3;     // 0x0F28 (size: 0x20)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_3;                                  // 0x0F48 (size: 0x128)
    FAnimNode_Slot AnimGraphNode_Slot_3;                                              // 0x1070 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_8;                          // 0x10B8 (size: 0x48)
    FAnimNode_StateResult AnimGraphNode_StateResult_2;                                // 0x1100 (size: 0x20)
    FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_2;     // 0x1120 (size: 0x20)
    FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_2;     // 0x1140 (size: 0x20)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_2;                                  // 0x1160 (size: 0x128)
    FAnimNode_Slot AnimGraphNode_Slot_2;                                              // 0x1288 (size: 0x48)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_5;                        // 0x12D0 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_7;                          // 0x1318 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_6;                          // 0x1360 (size: 0x48)
    FAnimNode_StateResult AnimGraphNode_StateResult_1;                                // 0x13A8 (size: 0x20)
    FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_1;     // 0x13C8 (size: 0x20)
    FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_1;     // 0x13E8 (size: 0x20)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone_1;                                  // 0x1408 (size: 0x128)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_5;                          // 0x1530 (size: 0x48)
    FAnimNode_StateResult AnimGraphNode_StateResult;                                  // 0x1578 (size: 0x20)
    FAnimNode_StateMachine AnimGraphNode_StateMachine;                                // 0x1598 (size: 0xC8)
    FAnimNode_Slot AnimGraphNode_Slot_1;                                              // 0x1660 (size: 0x48)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_2;                            // 0x16A8 (size: 0x28)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_4;                        // 0x16D0 (size: 0x48)
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone;                                    // 0x1718 (size: 0x128)
    FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;       // 0x1840 (size: 0x20)
    FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;       // 0x1860 (size: 0x20)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_4;                          // 0x1880 (size: 0x48)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_3;                        // 0x18C8 (size: 0x48)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_2;                        // 0x1910 (size: 0x48)
    FAnimNode_Slot AnimGraphNode_Slot;                                                // 0x1958 (size: 0x48)
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer;                        // 0x19A0 (size: 0x70)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_1;                        // 0x1A10 (size: 0x48)
    FAnimNode_SequenceEvaluator AnimGraphNode_SequenceEvaluator;                      // 0x1A58 (size: 0x40)
    FAnimNode_BlendListByEnum AnimGraphNode_BlendListByEnum;                          // 0x1A98 (size: 0x48)
    FAnimNode_LayeredBoneBlend AnimGraphNode_LayeredBoneBlend;                        // 0x1AE0 (size: 0xF0)
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool;                          // 0x1BD0 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_3;                          // 0x1C18 (size: 0x48)
    FAnimNode_SaveCachedPose AnimGraphNode_SaveCachedPose;                            // 0x1C60 (size: 0x80)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose_1;                            // 0x1CE0 (size: 0x28)
    FAnimNode_UseCachedPose AnimGraphNode_UseCachedPose;                              // 0x1D08 (size: 0x28)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_2;                          // 0x1D30 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_1;                          // 0x1D78 (size: 0x48)
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer;                            // 0x1DC0 (size: 0x48)
    bool ViewingWristwatch;                                                           // 0x1E08 (size: 0x1)
    bool Is Sprinting;                                                                // 0x1E09 (size: 0x1)
    bool IsJumping;                                                                   // 0x1E0A (size: 0x1)
    bool IsCrouching;                                                                 // 0x1E0B (size: 0x1)
    class UAnimSequence* FPArms_Walk;                                                 // 0x1E10 (size: 0x8)
    class UAnimSequence* FPArms_Crouch_Walk;                                          // 0x1E18 (size: 0x8)
    class UAnimSequence* FPArms_Sprint;                                               // 0x1E20 (size: 0x8)
    class UAnimSequence* FPArms_Crouch_Idle;                                          // 0x1E28 (size: 0x8)
    class UAnimSequence* FPArms_Idle;                                                 // 0x1E30 (size: 0x8)
    class UAnimSequence* FPArms_AltIdle;                                              // 0x1E38 (size: 0x8)
    class UAnimSequence* FPArms_AltWalk;                                              // 0x1E40 (size: 0x8)
    class UAnimSequence* FPArms_AltCrouchIdle;                                        // 0x1E48 (size: 0x8)
    class UAnimSequence* FPArms_AltCrouchWalk;                                        // 0x1E50 (size: 0x8)
    bool IsWalking;                                                                   // 0x1E58 (size: 0x1)
    bool RecentlyPunched;                                                             // 0x1E59 (size: 0x1)
    bool Unarmed;                                                                     // 0x1E5A (size: 0x1)
    class UAnimMontage* FPArms_UseItem;                                               // 0x1E60 (size: 0x8)
    class UAnimMontage* FPArms_Reload;                                                // 0x1E68 (size: 0x8)
    class UAnimMontage* FPArms_BadReload;                                             // 0x1E70 (size: 0x8)
    class UAnimMontage* FPArms_Equip;                                                 // 0x1E78 (size: 0x8)
    class UAnimMontage* FPArms_Stow;                                                  // 0x1E80 (size: 0x8)
    bool Is Plug Placement Mode;                                                      // 0x1E88 (size: 0x1)
    double Speed;                                                                     // 0x1E90 (size: 0x8)
    bool InDeployMode;                                                                // 0x1E98 (size: 0x1)
    bool ShieldBlocking;                                                              // 0x1E99 (size: 0x1)
    bool HasShield;                                                                   // 0x1E9A (size: 0x1)
    bool HasWalkAnim;                                                                 // 0x1E9B (size: 0x1)
    bool RecentlyUsedItem;                                                            // 0x1E9C (size: 0x1)
    bool RecentlyBlocked;                                                             // 0x1E9D (size: 0x1)
    FVector RightArmBlockOffset;                                                      // 0x1EA0 (size: 0x18)
    FRotator RightArmBlockRotation;                                                   // 0x1EB8 (size: 0x18)
    bool IsDeadDBNO;                                                                  // 0x1ED0 (size: 0x1)
    bool FishMode;                                                                    // 0x1ED1 (size: 0x1)
    double FishXAxis;                                                                 // 0x1ED8 (size: 0x8)
    double FishYAxis;                                                                 // 0x1EE0 (size: 0x8)
    double ReelProgress;                                                              // 0x1EE8 (size: 0x8)
    bool FishingReeling;                                                              // 0x1EF0 (size: 0x1)
    FTransform OffhandIdleTransform;                                                  // 0x1F00 (size: 0x60)
    FTransform OffhandBlockTransform;                                                 // 0x1F60 (size: 0x60)
    class UAnimSequenceBase* Offhand_Equip;                                           // 0x1FC0 (size: 0x8)
    class UAnimSequenceBase* Offhand_Walk;                                            // 0x1FC8 (size: 0x8)
    class UAnimSequenceBase* Offhand_Idle;                                            // 0x1FD0 (size: 0x8)
    class UAnimSequenceBase* Offhand_Block;                                           // 0x1FD8 (size: 0x8)
    class UAnimSequenceBase* Offhand_BlockHit;                                        // 0x1FE0 (size: 0x8)
    class UAnimSequenceBase* Offhand_Offscreen;                                       // 0x1FE8 (size: 0x8)
    bool AltAnimState;                                                                // 0x1FF0 (size: 0x1)

    void AnimGraph(FPoseLink& AnimGraph);
    void UpdateWristwatch(class AAbiotic_PlayerCharacter_C* Player);
    void EvaluateFPState();
    void TickFishing(double DeltaTime);
    void LoadAnimationReference(const TSoftObjectPtr<UObject>& SoftObjectReference, bool& Valid, class UObject*& Object);
    void LoadAndSetAnimData(FAbiotic_FPAnimationStruct FPAnimationData);
    void EvaluateGraphExposedInputs_ExecuteUbergraph_FPArms_AnimBP_AnimGraphNode_TransitionResult_89342EF84EE9BBDC88DD17B2D289DC64();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_FPArms_AnimBP_AnimGraphNode_SequencePlayer_30896D9B4152FE04F2FB9684EB3EA6E9();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_FPArms_AnimBP_AnimGraphNode_SequencePlayer_475C02CC407DCF037538A299972D6FDA();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_FPArms_AnimBP_AnimGraphNode_SequencePlayer_A5082A464DD018B151A45E8222BD7E21();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_FPArms_AnimBP_AnimGraphNode_SequencePlayer_18B4CA234EC445B810209B88D6F4CD73();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_FPArms_AnimBP_AnimGraphNode_ModifyBone_2F609C5049BBFCC172102E9988C116F5();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_FPArms_AnimBP_AnimGraphNode_ModifyBone_71BF1AD247F503E76F2EC7B7D5E8A1AA();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_FPArms_AnimBP_AnimGraphNode_BlendListByBool_2148D2384E5860B499F616B0C7ED9568();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_FPArms_AnimBP_AnimGraphNode_ModifyBone_4232E55949A46B0BAEA59E8CFA0DD8B0();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_FPArms_AnimBP_AnimGraphNode_ModifyBone_B7ACA42E4E530CC1EE8CB787E03CA72D();
    void BlueprintUpdateAnimation(float DeltaTimeX);
    void Set_RecentlyPunched();
    void PlayEquipAnim();
    void BlueprintBeginPlay();
    void OnBlockReaction_Event();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_FPArms_AnimBP_AnimGraphNode_ModifyBone_5609D41B44E746D7F7660094CE67E14B();
    void ExecuteUbergraph_FPArms_AnimBP(int32 EntryPoint);
}; // Size: 0x1FF1

#endif
